import type { Metadata } from "next";
import { Black_Han_Sans, IBM_Plex_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import HalftoneCursor from "./components/HalftoneCursor";

const blackHanSans = Black_Han_Sans({
  weight: "400",
  variable: "--font-black-han-sans",
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["400", "500", "700"],
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  weight: ["400", "700"],
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${blackHanSans.variable} ${ibmPlexMono.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <HalftoneCursor />
        {children}
      </body>
    </html>
  );
}
